#! /usr/bin/env escript
%% -*- erlang -*-

main([Expr]) ->
    Terms = grammar:parse(Expr),
    Prog = compiler:program(Terms, []),
% ff line may be useful to see if a generated cerl() might be
% malformed
% io:format("~w", [Prog]), io:nl().
    io:put_chars(core_pp:format(Prog)), io:nl().
